In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('pynb/glass.csv')

In [4]:
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [5]:
y = data['Type']

for i in range(9):
    max = data.iloc[:,i].max()
    min = data.iloc[:,i].min()
    for j in range(len(data)):
        data.iloc[j,i] = (data.iloc[j,i] - min) / (max-min)

In [6]:
data.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516523   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [7]:
X = data.iloc[:,:9]
tempX = X
X.head(1)

RI     Na    Mg   Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.1  71.78  0.06  8.75  0.0  0.0

In [8]:
ones = np.ones(214)
temp = pd.DataFrame({'Column1': ones[:]})
inp = np.concatenate((temp,X), axis = 1)

In [9]:
inp

array([[ 1.     ,  1.52101, 13.64   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.     ,  1.51761, 13.89   , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.     ,  1.51618, 13.53   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.     ,  1.52065, 14.36   , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.     ,  1.51651, 14.38   , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.     ,  1.51711, 14.23   , ...,  8.62   ,  1.67   ,  0.     ]])

In [10]:
class Neural:
        
    def __init__(self):
        np.random.seed(10)
        self.wh = np.random.rand(7,10)
        self.wout = np.random.rand(7,8)
    
    def sigmoid(self, x, w):
        z = self.hypo(x,w)
        res = 1/(1 + np.exp(-z))
        return res
    
    def sigmoid_derivative(self, x, w):
        return self.sigmoid(x, w) * (1 - self.sigmoid(x, w))
    
    def hypo(self,x,w):
        res = 0
        for i in range(len(x)):
            res += x[i]*w[i]
        return res
    
    def fwdprop(self, inputs):
        z2 = []
        for i in range(7):
            z2.append(self.sigmoid(inputs, self.wh[i]))
        return z2
    
    def fwdpropout(self, inputs):
        inputs.insert(0,1)
        z3 = []
        for i in range(7):
            z3.append(self.sigmoid(inputs, self.wout[i]))
        return z3
    
    def finddeltaout(self, inputs, output):
        error = []
        if output == 1:
            for i in range(len(inputs)):
                if i == 0:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
        
        if output == 2:
            for i in range(len(inputs)):
                if i == 1:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
                    
        if output == 3:
            for i in range(len(inputs)):
                if i == 2:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
                    
        if output == 4:
            for i in range(len(inputs)):
                if i == 3:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
        
        if output == 5:
            for i in range(len(inputs)):
                if i == 4:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
        
        if output == 6:
            for i in range(len(inputs)):
                if i == 5:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
        
        if output == 7:
            for i in range(len(inputs)):
                if i == 6:
                    error.append(inputs[i] - 1)
                else:
                    error.append(inputs[i] - 0)
        return error
    
        
    def change_weighttoout(self, inputs, inputsh, errors):
        lr = 0.03
        for i in range(7):
            for j in range(8):
                if j == 7:
                    self.wout[i][j] = self.wout[i][j] - lr*errors[i]*(inputs[i]*(1-inputs[i]))
                    break
                self.wout[i][j] = self.wout[i][j] - lr*errors[i]*inputsh[j]*(inputs[i]*(1-inputs[i]))
            
    def change_weightin(self, errors, inputsh, inputso, inputs):
        lr = 0.03
        j = 0
        for i in range(7):
            for m in range(7):
                sum = 0
                sum = sum + (error[m] * (inputso[m]*(1-inputso[m])) * self.wout[i][m])
            for j in range(10):
                self.wh[i][j] = self.wh[i][j] - lr*inputs[j]*inputsh[i]*(1-inputsh[i])*sum
                

In [11]:
network = Neural()
neterror = []

In [13]:
for i in range(10):
    for j in range(214):
        z2 = network.fwdprop(inp[j])
        z3 = (network.fwdpropout(network.fwdprop(inp[j])))
        temperror = 0
        error = network.finddeltaout(z3,y[j])
        for i in range(len(error)):
            temperror += error[i]
        neterror.append(temperror)
        network.change_weighttoout(z3, z2, error)
        network.change_weightin(error, z2, z3, inp[j])

In [14]:
neterror

[5.769605965127671,
 5.767548869735288,
 5.765444089130063,
 5.76329001099633,
 5.7610849587378645,
 5.758827189035054,
 5.756514889367275,
 5.754146175510824,
 5.751719089024859,
 5.74923159474016,
 5.746681578268264,
 5.744066843551547,
 5.741385110478287,
 5.738634012590579,
 5.735811094917284,
 5.732913811968963,
 5.729939525937071,
 5.726885505145481,
 5.723748922808869,
 5.720526856159372,
 5.717216286010589,
 5.713814096836015,
 5.710317077447694,
 5.706721922369999,
 5.703025234012938,
 5.699223525759194,
 5.695313226089005,
 5.691290683876725,
 5.687152175002372,
 5.682893910430024,
 5.67851204591252,
 5.674002693487607,
 5.6693619349343125,
 5.6645858373587625,
 5.65967047107547,
 5.654611929942135,
 5.649406354292393,
 5.644049956590658,
 5.638539049905072,
 5.632870079257675,
 5.627039655864188,
 5.621044594218375,
 5.614881951907389,
 5.60854907196431,
 5.602043627472814,
 5.595363668036958,
 5.588507667618406,
 5.581474573126075,
 5.574263853022622,
 5.566875545092706,
 5

In [21]:
network.wout

array([[-5.96937328e-01, -2.07404358e-01, -3.21969665e-01,
        -4.05393653e-04, -2.90549387e-01, -5.93799181e-01,
         2.43018638e-01,  1.26344050e-01],
       [ 3.05369081e-01, -1.55218418e-01,  3.28500030e-02,
        -5.92609340e-02,  2.51090866e-02, -3.10511900e-01,
        -2.71856252e-01, -5.47327779e-01],
       [-4.26072406e-01, -4.87059092e-01, -1.71556778e-01,
        -1.63627947e-01, -2.54002720e-01, -4.36336991e-01,
        -6.64883906e-01,  2.49684179e-01],
       [-6.29940936e-01, -4.74600149e-01,  7.43194593e-03,
        -5.28874955e-01, -6.51375975e-01, -4.49851794e-01,
        -3.91512350e-01, -1.15715029e-01],
       [-6.99913377e-01, -3.03479843e-01,  1.39384683e-02,
        -4.94078399e-02, -1.81988670e-01, -7.30916237e-01,
        -4.17354259e-01, -2.04819966e-01],
       [-3.43969031e-01, -1.31364750e-01,  2.97680221e-02,
        -4.84505170e-01, -5.93221233e-01, -3.05883016e-01,
        -5.35635130e-01, -4.64796095e-01],
       [ 1.85001670e-01, -3.354604

In [22]:
network.wh

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
        0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
        0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
        0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
        0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264,
        0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ],
       [0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445,
        0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413],
       [0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177,
        0.35718176, 0.07961309, 0.30545992, 0.33071931, 0.7738303 ]])