In [1]:
import pandas as pd
import numpy as np

In [11]:
x = np.random.rand(3,2)

In [12]:
x

array([[0.88710522, 0.48021329],
       [0.74160368, 0.6514132 ],
       [0.51763972, 0.46971006]])

In [32]:
ones = np.ones(3)

In [33]:
ones

array([1., 1., 1.])

In [36]:
dataset = pd.DataFrame({'Column1': ones[:]})

In [37]:
dataset

Column1
0      1.0
1      1.0
2      1.0

In [42]:
np.concatenate((dataset,x), axis = 1)

array([[1.        , 0.88710522, 0.48021329],
       [1.        , 0.74160368, 0.6514132 ],
       [1.        , 0.51763972, 0.46971006]])

In [43]:
np.array([[0, 1, 1, 0]]).T

array([[0],
       [1],
       [1],
       [0]])